### ISSUE TITLE
how to make preview work on remote server?

### ISSUE THREAD

**Issue by yech1990** [instant-markdown/vim-instant-markdown#92]
> I write makedown file on a remote server through ssh portal. The server has a public IP address and all the ports are accessable. 

when I press F12 to activate preview mode, I can visit the webpage though "ip:port", but the page is empty.

**Comment by hallzy** [comment]
+1

**Comment by hallzy** [comment]
btw... I found a pull request on the server repo for this project and someone had made a change to make this work. You can try using that. I also have a fork that has this change and also does not open up a browser automatically. You can find it [here](http://github.com/hallzy/instant-markdown-d).

Feel free to use it, or make the change yourself. The PR I am referring to is [here](https://github.com/suan/instant-markdown-d/pull/29).

if you decide to use mine instead, you need to install it again obviously. The npm command would now be `sudo npm -g install hallzy/instant-markdown-d`

**Comment by suan** [comment]
https://github.com/suan/instant-markdown-d/pull/29 has been merged which _partially_ solves this. However as @hallzy alludes to you still need a way to prevent the initial browser open. Open to suggestions on how we can improve the experience for this use-case, perhaps allowing multiple sockets/browser windows, so you can open/close browser windows at will and things will still work?

**Comment by hallzy** [comment]
That is what I would have liked to do, but I am not very familiar with almost any of this so I would not even know where to start. I think being able to open multiple browsers connected to the same socket would be nice.

I have not tried to do this through ssh with a computer running something like ubuntu-server though, which to my understanding does not have a web browser, so if we still open up the browser automatically in this situation I don't know what would happen (ie, would it just fail to open, or would it cause the whole thing to fail and we can't even connect from a different computer now?)

So if it is determined that we can do this and have no problems, then we can do that, otherwise there may need to be another way to say that we don't want the browser opening up automatically, or at least if it fails to open up a browser, we can still continue.

I like the idea of having a tab open up automatically in general so it would be nice to keep that feature I think. We just need a way to make sure that it wont have a negative effect on anything over ssh if we allow multiple browsers to connect to the same socket, or we would need to be able to tell it not to open it.

What I personally would like in a perfect world, is the ability to open a number of browsers connected to that socket, and let it try to open up a browser automatically, and if it fails because it is a terminal based OS and does not have a browser, that the application won't fail and I can still connect from another browser. This way I would still have the ability to open a browser automatically, but I can also work over ssh.

**Comment by suan** [comment]
Yes @hallzy what I have in mind is for the server to initiate a new websocket to whatever sends it a `GET` request at anytime (which is what opening a browser window with the address will do), and broadcasting to all connected websockets anytime there's a change. That way windows can come and go at anytime and any one of them failing won't affect the rest of them.

I've created a new issue for myself here: https://github.com/suan/instant-markdown-d/issues/33

**Comment by hallzy** [comment]
nice! I look forward to it :)
